# Generated by Django 3.1.5 on 2022-10-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Websites',
        ),
    ]
